; Using seed 154923
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
	.byte 	1     ; *** Load Float 6.904571533203124e-06 ***
	.dword 	$e7add15f
	.byte 	$6f,$0
	.byte 	1     ; *** Load Float 9.138083 ***
	.dword 	$92359685
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 121997447355885.94 ***
	.dword 	$dde97d06
	.byte 	$af,$0
	.byte 	1     ; *** Load Float 9.952853 ***
	.dword 	$9f3ee2c9
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 121997447355895.89 ***
	.dword 	$dde97d06
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1555655021675.1514 ***
	.dword 	$b51a21ea
	.byte 	$a9,$80
	.byte 	1     ; *** Load Float 9.283651 ***
	.dword 	$9489d5a1
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1555655021665.8677 ***
	.dword 	$b51a21ea
	.byte 	$a9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7675073.00352 ***
	.dword 	$ea398201
	.byte 	$97,$0
	.byte 	1     ; *** Load Float 423.55 ***
	.dword 	$d3c66666
	.byte 	$89,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 458.77 ***
	.dword 	$e5628f5c
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 459.77 ***
	.dword 	$e5e28f5c
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -253.42 ***
	.dword 	$fd6b851e
	.byte 	$88,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 238.42 ***
	.dword 	$ee6b851e
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 62.74 ***
	.dword 	$faf5c28f
	.byte 	$86,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.971111111111111 ***
	.dword 	$df13579b
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.539232006412931e-14 ***
	.dword 	$f976ff3a
	.byte 	$54,$0
	.byte 	1     ; *** Load Float 6.4887 ***
	.dword 	$cfa36e2e
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 8.536736181997828e-15 ***
	.dword 	$99c8bf34
	.byte 	$52,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.268232 ***
	.dword 	$a2556d19
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 17.268232 ***
	.dword 	$8a2556d1
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 748.57 ***
	.dword 	$bb247ae1
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 1.2653908925130964e-12 ***
	.dword 	$b21682f9
	.byte 	$59,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 847.45 ***
	.dword 	$d3dccccc
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -1343559.303168 ***
	.dword 	$a4023a6c
	.byte 	$95,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1342711.853168 ***
	.dword 	$a3e7bed3
	.byte 	$95,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.301443 ***
	.dword 	$84d2b5e5
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.301443 ***
	.dword 	$84d2b5e5
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -114073.796608 ***
	.dword 	$decce5f7
	.byte 	$91,$80
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -114065.796608 ***
	.dword 	$dec8e5f7
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.193001 ***
	.dword 	$8c5a20dd
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 3.594397 ***
	.dword 	$e60a99b6
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.908037 ***
	.dword 	$8e8751ce
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 1.837815 ***
	.dword 	$eb3d859c
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -50520.588288 ***
	.dword 	$c558969a
	.byte 	$90,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 50500.588288 ***
	.dword 	$c544969a
	.byte 	$90,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.616753 ***
	.dword 	$99de3864
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.734155 ***
	.dword 	$bbf19503
	.byte 	$80,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 13.09907717035231 ***
	.dword 	$d195d1f1
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.251196 ***
	.dword 	$a809cc31
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.251196 ***
	.dword 	$a809cc31
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.124819 ***
	.dword 	$81ff4235
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 2432243.3351680003 ***
	.dword 	$9473cd57
	.byte 	$96,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -2432235.2103490005 ***
	.dword 	$9473acd7
	.byte 	$96,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.553686 ***
	.dword 	$e36f9767
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3.553686 ***
	.dword 	$e36f9767
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.983425 ***
	.dword 	$df7837b4
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 383739339349264.7 ***
	.dword 	$ae812381
	.byte 	$b1,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.8198355716779816e-14 ***
	.dword 	$a3ea8d22
	.byte 	$53,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.630112 ***
	.dword 	$9429e0a4
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.2011826038360596e-09 ***
	.dword 	$a516db0d
	.byte 	$63,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.630112001201182 ***
	.dword 	$9429e0a4
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.493712 ***
	.dword 	$bf31f46e
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -785.58 ***
	.dword 	$c4651eb8
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -784.0862880000001 ***
	.dword 	$c40585be
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 939400744539.2589 ***
	.dword 	$dab8a5ce
	.byte 	$a8,$0
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 55258867325.83876 ***
	.dword 	$cddaf667
	.byte 	$a4,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -33701266.194432005 ***
	.dword 	$808f648c
	.byte 	$9a,$80
	.byte 	1     ; *** Load Float -33701266.194432005 ***
	.dword 	$808f648c
	.byte 	$9a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 12.0 ***
	.dword 	$c0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -0.275222 ***
	.dword 	$8ce9e5e2
	.byte 	$7f,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.390698254108429e-10 ***
	.dword 	$afaa8a82
	.byte 	$62,$80
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.086418703198433e-08 ***
	.dword 	$baa5332a
	.byte 	$66,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.7 ***
	.dword 	$b3333333
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 8.406948 ***
	.dword 	$8682dbe7
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.08326446172856071 ***
	.dword 	$aa868ee0
	.byte 	$7d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1319345233.854464 ***
	.dword 	$9d4738a3
	.byte 	$9f,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 292.51 ***
	.dword 	$924147ae
	.byte 	$89,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0341868654063109 ***
	.dword 	$8c0786cd
	.byte 	$7c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.104175165295601e-11 ***
	.dword 	$9c38f366
	.byte 	$5f,$80
	.byte 	1     ; *** Load Float -772.72 ***
	.dword 	$c12e147a
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 9.193724978382339e-14 ***
	.dword 	$cf063757
	.byte 	$55,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -24989.401088 ***
	.dword 	$c33acd5b
	.byte 	$8f,$80
	.byte 	1     ; *** Load Float 1.339027 ***
	.dword 	$ab653c9a
	.byte 	$81,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -24988.062060999997 ***
	.dword 	$c3381fc6
	.byte 	$8f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -254.64 ***
	.dword 	$fea3d70a
	.byte 	$88,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 258.64 ***
	.dword 	$8151eb85
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -168.67 ***
	.dword 	$a8ab851e
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 560.23 ***
	.dword 	$8c0eb851
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -804.37 ***
	.dword 	$c917ae14
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -896.47 ***
	.dword 	$e01e147a
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1700.8400000000001 ***
	.dword 	$d49ae147
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.1105804443359375e-06 ***
	.dword 	$8da37ef5
	.byte 	$6e,$0
	.byte 	1     ; *** Load Float -879.12 ***
	.dword 	$dbc7ae14
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 879.1200021105805 ***
	.dword 	$dbc7ae1d
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.662728 ***
	.dword 	$d4d44567
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 1.662728 ***
	.dword 	$d4d44567
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 971.52 ***
	.dword 	$f2e147ae
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 509.43 ***
	.dword 	$feb70a3d
	.byte 	$89,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.9070726105647489 ***
	.dword 	$f41af48e
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.976190540328388e-14 ***
	.dword 	$e0a4d2b2
	.byte 	$55,$80
	.byte 	1     ; *** Load Float 1.971712 ***
	.dword 	$fc610f0e
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.216744 ***
	.dword 	$9bbe4473
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0760465 ***
	.dword 	$9bbe4473
	.byte 	$7d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -574.1 ***
	.dword 	$8f866666
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.130259811878204e-10 ***
	.dword 	$df7b9e06
	.byte 	$62,$80
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -308.55 ***
	.dword 	$9a466666
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 2.89 ***
	.dword 	$b8f5c28f
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -305.66 ***
	.dword 	$98d47ae1
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 363.34 ***
	.dword 	$b5ab851e
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 6.292174 ***
	.dword 	$c9597d49
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 357.047826 ***
	.dword 	$b2861f29
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.3650823384523392e-09 ***
	.dword 	$bb9d909f
	.byte 	$63,$0
	.byte 	1     ; *** Load Float 1.3650823384523392e-09 ***
	.dword 	$bb9d909f
	.byte 	$63,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.2 ***
	.dword 	$cccccccc
	.byte 	$7e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.692292 ***
	.dword 	$ac4e831a
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -2.9623291015625e-05 ***
	.dword 	$f87f8876
	.byte 	$71,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 2.6922623767089844 ***
	.dword 	$ac4e06db
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4384903911.17824 ***
	.dword 	$82ae2973
	.byte 	$a1,$80
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.0764095932245254e-09 ***
	.dword 	$93f0cbaf
	.byte 	$63,$0
	.byte 	1     ; *** Load Float 1.0764095932245254e-09 ***
	.dword 	$93f0cbaf
	.byte 	$63,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.95094 ***
	.dword 	$9e6e19b9
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 4.95094 ***
	.dword 	$9e6e19b9
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.769527 ***
	.dword 	$b13fee2c
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -0.27705 ***
	.dword 	$8dd97f62
	.byte 	$7f,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -9.996487998556217 ***
	.dword 	$9ff19d66
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.099943 ***
	.dword 	$ccaeea63
	.byte 	$7d,$0
	.byte 	1     ; *** Load Float 1.9278377294540404e-09 ***
	.dword 	$847ae147
	.byte 	$64,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 51842018.896633826 ***
	.dword 	$c5c2f8b9
	.byte 	$9a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.043612 ***
	.dword 	$82ca89fc
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 8.085538 ***
	.dword 	$815e5d18
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 16.523702483256 ***
	.dword 	$84308aed
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 3.273153305053711e-07 ***
	.dword 	$afb9e060
	.byte 	$6b,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1.9638919830322264e-06 ***
	.dword 	$83cb6848
	.byte 	$6e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 32674.545663999997 ***
	.dword 	$ff451761
	.byte 	$8f,$0
	.byte 	1     ; *** Load Float -1893053358797.7502 ***
	.dword 	$dc6162f1
	.byte 	$a9,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -6.185465841642566e+16 ***
	.dword 	$dbc07bee
	.byte 	$b8,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -944.79 ***
	.dword 	$ec328f5c
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 13843.562496 ***
	.dword 	$d84e3ffe
	.byte 	$8e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -13079259.41059584 ***
	.dword 	$c792db69
	.byte 	$98,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 320.4 ***
	.dword 	$a0333333
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -9.66736024565762e-16 ***
	.dword 	$8b524399
	.byte 	$4f,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3.097422222708701e-13 ***
	.dword 	$ae5e8f01
	.byte 	$57,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.121901 ***
	.dword 	$c7cd39da
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 9.979613 ***
	.dword 	$9fac7eae
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -6.857712000000001 ***
	.dword 	$db72606f
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -8.598752319812775e-10 ***
	.dword 	$ec5c5718
	.byte 	$62,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -12.999999999140124 ***
	.dword 	$cfffffff
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -611.39 ***
	.dword 	$98d8f5c2
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -21.15 ***
	.dword 	$a9333333
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 28.90732860520095 ***
	.dword 	$e742357f
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -141.35 ***
	.dword 	$8d599999
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 0.0008858779296875 ***
	.dword 	$e83a42f1
	.byte 	$76,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1641298129.846272 ***
	.dword 	$c3a871a3
	.byte 	$9f,$80
	.byte 	1     ; *** Load Float 12.0 ***
	.dword 	$c0000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1641298117.846272 ***
	.dword 	$c3a8718b
	.byte 	$9f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -165.86 ***
	.dword 	$a5dc28f5
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1492.7400000000002 ***
	.dword 	$ba97ae14
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.6120357031468301e-12 ***
	.dword 	$e2dfb506
	.byte 	$59,$80
	.byte 	1     ; *** Load Float -142039859878.42868 ***
	.dword 	$8448f10a
	.byte 	$a6,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 142039859878.42868 ***
	.dword 	$8448f10a
	.byte 	$a6,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 809.72 ***
	.dword 	$ca6e147a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 8.094702934613451e-13 ***
	.dword 	$e3d87b56
	.byte 	$58,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 7.979307 ***
	.dword 	$ff567ba2
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -11.979307 ***
	.dword 	$bfab3dd1
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 373.6 ***
	.dword 	$bacccccc
	.byte 	$89,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3736.0 ***
	.dword 	$e9800000
	.byte 	$8c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 4.632250139025018e-16 ***
	.dword 	$8583f91e
	.byte 	$4e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3.242575097317513e-15 ***
	.dword 	$e9a6f3f5
	.byte 	$50,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float -631.48 ***
	.dword 	$9ddeb851
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1894.44 ***
	.dword 	$ecce147a
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 77.0 ***
	.dword 	$9a000000
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -0.734789 ***
	.dword 	$bc1b21c4
	.byte 	$80,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 5.443739631377171 ***
	.dword 	$ae331d74
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -97730907.078656 ***
	.dword 	$ba682b62
	.byte 	$9b,$80
	.byte 	1     ; *** Load Float -43019.993087999996 ***
	.dword 	$a80bfe3b
	.byte 	$90,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -97687887.085568 ***
	.dword 	$ba5329e2
	.byte 	$9b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.0002339794921875 ***
	.dword 	$f5586445
	.byte 	$74,$80
	.byte 	1     ; *** Load Float 399.23 ***
	.dword 	$c79d70a3
	.byte 	$89,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -0.09341163266601563 ***
	.dword 	$bf4e991a
	.byte 	$7d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.280274244043539e-16 ***
	.dword 	$eea9a3d2
	.byte 	$4e,$80
	.byte 	1     ; *** Load Float 0.569435 ***
	.dword 	$91c67dfe
	.byte 	$80,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -925.06 ***
	.dword 	$e743d70a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -914.06 ***
	.dword 	$e483d70a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float -7170.686976 ***
	.dword 	$e0157eed
	.byte 	$8d,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -7172.686976 ***
	.dword 	$e0257eed
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.7193078994750978e-07 ***
	.dword 	$b89bf9c6
	.byte 	$6a,$80
	.byte 	1     ; *** Load Float 6.527386 ***
	.dword 	$d0e0589a
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -6.5273861719307895 ***
	.dword 	$d0e058f7
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19114150655.42656 ***
	.dword 	$8e69595f
	.byte 	$a3,$80
	.byte 	1     ; *** Load Float -1.5039518075354862e-14 ***
	.dword 	$8776c482
	.byte 	$53,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.00028746761427734374 ***
	.dword 	$96b74004
	.byte 	$75,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 523.66 ***
	.dword 	$82ea3d70
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -11646.5664 ***
	.dword 	$b5fa43fe
	.byte 	$8e,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -11122.9064 ***
	.dword 	$adcba027
	.byte 	$8e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18396687.106048003 ***
	.dword 	$8c5b078d
	.byte 	$99,$0
	.byte 	1     ; *** Load Float 4.073557 ***
	.dword 	$825a9435
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 18396691.179605003 ***
	.dword 	$8c5b0996
	.byte 	$99,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -7.216405868530273e-07 ***
	.dword 	$c1b6c376
	.byte 	$6c,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1.1546249389648438e-05 ***
	.dword 	$c1b6c376
	.byte 	$70,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.1004979498684406e-10 ***
	.dword 	$e6f3c2da
	.byte 	$60,$80
	.byte 	1     ; *** Load Float 952.22 ***
	.dword 	$ee0e147a
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -952.2200000002101 ***
	.dword 	$ee0e147a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.042451 ***
	.dword 	$82b78466
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -1.2942164175910875e-12 ***
	.dword 	$b6250f84
	.byte 	$59,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -479.307776 ***
	.dword 	$efa76534
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 54.24 ***
	.dword 	$d8f5c28f
	.byte 	$86,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.228719234466553e-09 ***
	.dword 	$8d5e4a38
	.byte 	$66,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 9.999999991771281 ***
	.dword 	$9ffffffd
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 118035968533660.17 ***
	.dword 	$d6b4c7f3
	.byte 	$af,$0
	.byte 	1     ; *** Load Float 460.46 ***
	.dword 	$e63ae147
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 118035968534120.62 ***
	.dword 	$d6b4c7f3
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.687792 ***
	.dword 	$b602645e
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -728.49 ***
	.dword 	$b61f5c28
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 734.177792 ***
	.dword 	$b78b60f1
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -912.65 ***
	.dword 	$e4299999
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.012052813236180354 ***
	.dword 	$c57929ab
	.byte 	$7a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 154822777664905.94 ***
	.dword 	$8ccf7caa
	.byte 	$b0,$0
	.byte 	1     ; *** Load Float 1.0121657396666704e-11 ***
	.dword 	$b20fe479
	.byte 	$5c,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 154822777664905.94 ***
	.dword 	$8ccf7caa
	.byte 	$b0,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1918317936980.787 ***
	.dword 	$df525460
	.byte 	$a9,$80
	.byte 	1     ; *** Load Float -903.85 ***
	.dword 	$e1f66666
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -1918317936076.937 ***
	.dword 	$df52545e
	.byte 	$a9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.1513520803418942e-14 ***
	.dword 	$cf68be2f
	.byte 	$52,$80
	.byte 	1     ; *** Load Float -5.766227841377258e-09 ***
	.dword 	$c62046c7
	.byte 	$65,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -5.766239354898062e-09 ***
	.dword 	$c62060b4
	.byte 	$65,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -257.17 ***
	.dword 	$8095c28f
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -4114.72 ***
	.dword 	$8095c28f
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.0444564395584167e-12 ***
	.dword 	$92fe8251
	.byte 	$59,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 5744614875979.63 ***
	.dword 	$a730b754
	.byte 	$ab,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -9.013433555082883e-15 ***
	.dword 	$a25f2021
	.byte 	$52,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 15.999999999999991 ***
	.dword 	$ffffffff
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 222650554868.8261 ***
	.dword 	$cf5c0767
	.byte 	$a6,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -6.335158104775474e-13 ***
	.dword 	$b251a005
	.byte 	$58,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -6.335158104775474e-13 ***
	.dword 	$b251a005
	.byte 	$58,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 405.47 ***
	.dword 	$cabc28f5
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 32239088301275.87 ***
	.dword 	$ea91fb3f
	.byte 	$ad,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 179.33 ***
	.dword 	$b3547ae1
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 8.063902 ***
	.dword 	$8105be1a
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 22.238613514896386 ***
	.dword 	$b1e8ae33
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -634.09 ***
	.dword 	$9e85c28f
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -867.95 ***
	.dword 	$d8fccccc
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 550358.4155 ***
	.dword 	$865d66a5
	.byte 	$94,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.2640940733253955e-10 ***
	.dword 	$f8f09528
	.byte 	$60,$0
	.byte 	1     ; *** Load Float -6.34128600358963e-09 ***
	.dword 	$d9e28aa4
	.byte 	$65,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -6.1148765962570905e-09 ***
	.dword 	$d21b05fa
	.byte 	$65,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -823.78 ***
	.dword 	$cdf1eb85
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 10709.14 ***
	.dword 	$a7548f5c
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -899.77 ***
	.dword 	$e0f147ae
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -46911578.963968 ***
	.dword 	$b2f416bd
	.byte 	$9a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 123041578781994.12 ***
	.dword 	$dfcfb331
	.byte 	$af,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 123041578782012.12 ***
	.dword 	$dfcfb331
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.519662 ***
	.dword 	$8508919e
	.byte 	$80,$0
	.byte 	1     ; *** Load Float 0.043923 ***
	.dword 	$b3e89a88
	.byte 	$7c,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 11.831204608064112 ***
	.dword 	$bd4c9d33
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 799.98 ***
	.dword 	$c7feb851
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -782.98 ***
	.dword 	$c3beb851
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.910395 ***
	.dword 	$9d21f4b1
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 20790390491.709442 ***
	.dword 	$9ae685db
	.byte 	$a3,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -20790390486.799046 ***
	.dword 	$9ae685da
	.byte 	$a3,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.175477220589528e-14 ***
	.dword 	$c3f316e3
	.byte 	$53,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.9114471435546874e-05 ***
	.dword 	$f43ad9f0
	.byte 	$71,$80
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.00046583154296875 ***
	.dword 	$f43ad9f0
	.byte 	$75,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -1.1514052748680115e-08 ***
	.dword 	$c5cf56ea
	.byte 	$66,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1042204709.4908081 ***
	.dword 	$f87b2095
	.byte 	$9e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.38322 ***
	.dword 	$c435696e
	.byte 	$7f,$0
	.byte 	1     ; *** Load Float -16.83 ***
	.dword 	$86a3d70a
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.02277005347593583 ***
	.dword 	$ba884360
	.byte 	$7b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 445.52 ***
	.dword 	$dec28f5c
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 826.97 ***
	.dword 	$cebe147a
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 368431.6744 ***
	.dword 	$b3e5f594
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 6.4467010498046884e-06 ***
	.dword 	$d850bd87
	.byte 	$6f,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -50.57 ***
	.dword 	$ca47ae14
	.byte 	$86,$80
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -31.57 ***
	.dword 	$fc8f5c28
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 5.32348 ***
	.dword 	$aa59f2ba
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -10.67652 ***
	.dword 	$aad306a2
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 739.59 ***
	.dword 	$b8e5c28f
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 1.071297 ***
	.dword 	$89204295
	.byte 	$81,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 740.661297 ***
	.dword 	$b92a52b0
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	1     ; *** Load Float 0.550767 ***
	.dword 	$8cff10ec
	.byte 	$80,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -65.08 ***
	.dword 	$8228f5c2
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 812.12 ***
	.dword 	$cb07ae14
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 43473176834263.22 ***
	.dword 	$9e278d0c
	.byte 	$ae,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.1501344884598516e-13 ***
	.dword 	$817e5e9f
	.byte 	$56,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 118357412957063.75 ***
	.dword 	$d74a771c
	.byte 	$af,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1893718607313020.0 ***
	.dword 	$d74a771c
	.byte 	$b3,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2203.8528 ***
	.dword 	$89bda511
	.byte 	$8c,$0
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.608299 ***
	.dword 	$b3772f76
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 488.91 ***
	.dword 	$f4747ae1
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 494.518299 ***
	.dword 	$f742579f
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -169.05 ***
	.dword 	$a90ccccc
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 2.1222329139709471e-07 ***
	.dword 	$e3df7e80
	.byte 	$6a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -796566667.5279652 ***
	.dword 	$bdea922e
	.byte 	$9e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.8351058959960937e-07 ***
	.dword 	$cde54b48
	.byte 	$6b,$80
	.byte 	1     ; *** Load Float -6.861850619316101e-09 ***
	.dword 	$ebc579f2
	.byte 	$65,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -3.903724402189255e-07 ***
	.dword 	$d1946130
	.byte 	$6b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -95.29 ***
	.dword 	$be947ae1
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -113.29 ***
	.dword 	$e2947ae1
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 153.6 ***
	.dword 	$99999999
	.byte 	$88,$0
	.byte 	1     ; *** Load Float -6.91765222882168e-15 ***
	.dword 	$f93c1483
	.byte 	$51,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 153.6 ***
	.dword 	$99999999
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.384215 ***
	.dword 	$8c4b7d41
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -0.00016664111328125 ***
	.dword 	$aebc621b
	.byte 	$74,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -0.0007305904684643555 ***
	.dword 	$bf8518ac
	.byte 	$76,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -978.76 ***
	.dword 	$f4b0a3d7
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 9787.6 ***
	.dword 	$98ee6666
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.202204 ***
	.dword 	$933c3a42
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -5.356683686841279e-12 ***
	.dword 	$bc78b7a1
	.byte 	$5b,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 9.202203999994643 ***
	.dword 	$933c3a42
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -28.82 ***
	.dword 	$e68f5c28
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 8.839241 ***
	.dword 	$8d6d87f8
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -37.659241 ***
	.dword 	$96a31012
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 174764074700.11188 ***
	.dword 	$a2c3009b
	.byte 	$a6,$0
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3145753344602.0137 ***
	.dword 	$b71b60ae
	.byte 	$aa,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.9913068172172642e-13 ***
	.dword 	$e03382e4
	.byte 	$56,$0
	.byte 	1     ; *** Load Float 6.806797 ***
	.dword 	$d9d147f1
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2.92546820070771e-14 ***
	.dword 	$83c05a1c
	.byte 	$54,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 562340278621756.7 ***
	.dword 	$ffb90646
	.byte 	$b1,$0
	.byte 	1     ; *** Load Float 799.89 ***
	.dword 	$c7f8f5c2
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -500.47 ***
	.dword 	$fa3c28f5
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -1.011120502880658e-13 ***
	.dword 	$e3af20ea
	.byte 	$55,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 4949657321498012.0 ***
	.dword 	$8cad7f33
	.byte 	$b5,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.915044 ***
	.dword 	$ea4052d6
	.byte 	$80,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -2.084956 ***
	.dword 	$856feb4a
	.byte 	$82,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.01079 ***
	.dword 	$80b0c88a
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 38.20501 ***
	.dword 	$98d1ee24
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0125804073577456e-15 ***
	.dword 	$d9144cbe
	.byte 	$50,$0
	.byte 	1     ; *** Load Float 7.904345 ***
	.dword 	$fcf064ec
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -7.9043449999999975 ***
	.dword 	$fcf064ec
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.938395 ***
	.dword 	$de0754f3
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1097.13408 ***
	.dword 	$89244a62
	.byte 	$8b,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -213.71 ***
	.dword 	$d5b5c28f
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -214.71 ***
	.dword 	$d6b5c28f
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 4.460027 ***
	.dword 	$8eb88a8b
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.8968555571524567 ***
	.dword 	$e5985367
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.1525421142578126e-06 ***
	.dword 	$ace3ffef
	.byte 	$6f,$80
	.byte 	1     ; *** Load Float 8.120758 ***
	.dword 	$81ee9ff0
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -8.120763152542114 ***
	.dword 	$81eea557
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.08234 ***
	.dword 	$815143bf
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 115839.860736 ***
	.dword 	$e23fee2c
	.byte 	$91,$0
	.byte 	1     ; *** Load Float 830.97 ***
	.dword 	$cfbe147a
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 116670.830736 ***
	.dword 	$e3df6a55
	.byte 	$91,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 4.627366 ***
	.dword 	$941361dc
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 9.254732 ***
	.dword 	$941361dc
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0557421743869785e-10 ***
	.dword 	$def77f27
	.byte 	$61,$0
	.byte 	1     ; *** Load Float 5.79133 ***
	.dword 	$b952934a
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 7.003127389368208e-11 ***
	.dword 	$9a001a35
	.byte 	$5f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.0080643632099966e-14 ***
	.dword 	$e18b0d0e
	.byte 	$54,$80
	.byte 	1     ; *** Load Float -267.39 ***
	.dword 	$85b1eb85
	.byte 	$89,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1.339106330078721e-11 ***
	.dword 	$eb93fcd9
	.byte 	$5c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 751.3 ***
	.dword 	$bbd33333
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -539.03 ***
	.dword 	$86c1eb85
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -775.56 ***
	.dword 	$c1e3d70a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 8.950719 ***
	.dword 	$8f362520
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -766.6092809999999 ***
	.dword 	$bfa6fe75
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 54998121377.16941 ***
	.dword 	$cce24bba
	.byte 	$a4,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 54998121394.16941 ***
	.dword 	$cce24bbb
	.byte 	$a4,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -217774.555136 ***
	.dword 	$d4aba387
	.byte 	$92,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 217785.555136 ***
	.dword 	$d4ae6387
	.byte 	$92,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 139057887.707136 ***
	.dword 	$849dadfb
	.byte 	$9c,$0
	.byte 	1     ; *** Load Float -190.65 ***
	.dword 	$bea66666
	.byte 	$88,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 139057697.057136 ***
	.dword 	$849da210
	.byte 	$9c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.405891 ***
	.dword 	$867e878f
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 2.370076 ***
	.dword 	$97af533f
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.940605 ***
	.dword 	$f865bea0
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 1.940605 ***
	.dword 	$f865bea0
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3.7659477660249996 ***
	.dword 	$f10549c7
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -610.51 ***
	.dword 	$98a0a3d7
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 9768.16 ***
	.dword 	$98a0a3d7
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -134.22 ***
	.dword 	$863851eb
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 62003355.844608 ***
	.dword 	$ec8626f6
	.byte 	$9a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2.164721540820797e-06 ***
	.dword 	$9145a205
	.byte 	$6e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -210.47 ***
	.dword 	$d27851eb
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -629957885.689856 ***
	.dword 	$963193f6
	.byte 	$9e,$80
	.byte 	1     ; *** Load Float -238515139865168.8 ***
	.dword 	$d8eda22f
	.byte 	$b0,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.985681 ***
	.dword 	$9f8ab2e1
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 2.800490619847551e-12 ***
	.dword 	$c511276f
	.byte 	$5a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1780288412560.8687 ***
	.dword 	$cf40baad
	.byte 	$a9,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 672.34 ***
	.dword 	$a815c28f
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 703.24 ***
	.dword 	$afcf5c28
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.8611425168255664e-16 ***
	.dword 	$de946801
	.byte 	$4d,$80
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -6.563942278603463e-15 ***
	.dword 	$ec7dae81
	.byte 	$51,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 389729.4848 ***
	.dword 	$be4c2f83
	.byte 	$93,$0
	.byte 	1     ; *** Load Float 8.028369140624999e-05 ***
	.dword 	$a85dfa87
	.byte 	$73,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 389729.48488028365 ***
	.dword 	$be4c2f84
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.994077 ***
	.dword 	$bfcf7a91
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.74454 ***
	.dword 	$b7d3458c
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.24953700000000012 ***
	.dword 	$ff86a098
	.byte 	$7e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -466.44 ***
	.dword 	$e93851eb
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 468.44 ***
	.dword 	$ea3851eb
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 6.466601 ***
	.dword 	$ceee6538
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 90.532414 ***
	.dword 	$b5109891
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1714.098176 ***
	.dword 	$d6432441
	.byte 	$8b,$80
	.byte 	1     ; *** Load Float 991.85 ***
	.dword 	$f7f66666
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.949473 ***
	.dword 	$f310a99b
	.byte 	$80,$0
	.byte 	1     ; *** Load Float 7.1436 ***
	.dword 	$e4985f06
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 6.7826553228 ***
	.dword 	$d90b832c
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -763.23 ***
	.dword 	$beceb851
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 350.43 ***
	.dword 	$af370a3d
	.byte 	$89,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 65161.78944 ***
	.dword 	$fe89ca18
	.byte 	$90,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 65163.78944 ***
	.dword 	$fe8bca18
	.byte 	$90,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.968447 ***
	.dword 	$defd8490
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -424.649728 ***
	.dword 	$d4532a49
	.byte 	$89,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -417.68128099999996 ***
	.dword 	$d0d73437
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 130433140257.71826 ***
	.dword 	$f2f35e31
	.byte 	$a5,$0
	.byte 	1     ; *** Load Float 749.37 ***
	.dword 	$bb57ae14
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 130433139508.34827 ***
	.dword 	$f2f35e19
	.byte 	$a5,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.862819 ***
	.dword 	$f7386d2e
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -988.79 ***
	.dword 	$f7328f5c
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3819.51679901 ***
	.dword 	$eeb844cf
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.89841 ***
	.dword 	$fcbfc654
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 573.17 ***
	.dword 	$8f4ae147
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -856.42 ***
	.dword 	$d61ae147
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -286339990208123.0 ***
	.dword 	$82365cb3
	.byte 	$b1,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -286339990208979.44 ***
	.dword 	$82365cb3
	.byte 	$b1,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 913.01 ***
	.dword 	$e440a3d7
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 142.22 ***
	.dword 	$8e3851eb
	.byte 	$88,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 129848.2822 ***
	.dword 	$fd9c241f
	.byte 	$91,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -404684050695.979 ***
	.dword 	$bc721922
	.byte 	$a7,$80
	.byte 	1     ; *** Load Float 549825338207247.5 ***
	.dword 	$fa0817fc
	.byte 	$b1,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2.2250554504099554e+26 ***
	.dword 	$b80d61c4
	.byte 	$d8,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.06967 ***
	.dword 	$c23abc94
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 4.7080850601196286e-07 ***
	.dword 	$fcc36da8
	.byte 	$6b,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.751353 ***
	.dword 	$f0162ae4
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 1.063531494140625e-05 ***
	.dword 	$b26e5471
	.byte 	$70,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.373266 ***
	.dword 	$abf1cb89
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.778235 ***
	.dword 	$c73a68b1
	.byte 	$80,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 4.18166366551 ***
	.dword 	$85d03051
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.641380317276344e-13 ***
	.dword 	$ccfdd228
	.byte 	$57,$80
	.byte 	1     ; *** Load Float 25577423600.877567 ***
	.dword 	$be91105e
	.byte 	$a3,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -25577423600.877567 ***
	.dword 	$be91105e
	.byte 	$a3,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 57.04 ***
	.dword 	$e428f5c2
	.byte 	$86,$0
	.byte 	1     ; *** Load Float -0.039052 ***
	.dword 	$9ff4fd6d
	.byte 	$7c,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1460.6166137457747 ***
	.dword 	$b693bb4c
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.292822 ***
	.dword 	$a57b30f8
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 2.9226157494122165e-14 ***
	.dword 	$839f7729
	.byte 	$54,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 44235100021616.13 ***
	.dword 	$a0ed25b1
	.byte 	$ae,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.086063 ***
	.dword 	$c5820e62
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.000111688720703125 ***
	.dword 	$ea3a6ce3
	.byte 	$73,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 3.999888311279297 ***
	.dword 	$fffe2b8b
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.69968 ***
	.dword 	$b31e3a7d
	.byte 	$80,$0
	.byte 	1     ; *** Load Float 9.861915 ***
	.dword 	$9dca6762
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.07094768105383184 ***
	.dword 	$914d048e
	.byte 	$7d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 163877.486592 ***
	.dword 	$a0095f24
	.byte 	$92,$0
	.byte 	1     ; *** Load Float -84332014084837.88 ***
	.dword 	$9966277c
	.byte 	$af,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -84332013920960.39 ***
	.dword 	$99662777
	.byte 	$af,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8272691127.648256 ***
	.dword 	$f68b9fdb
	.byte 	$a1,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -435404796.1920135 ***
	.dword 	$cf9dffe1
	.byte 	$9d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 290.12 ***
	.dword 	$910f5c28
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -89845.53062399999 ***
	.dword 	$af7ac3eb
	.byte 	$91,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.003229097741257056 ***
	.dword 	$d39f4531
	.byte 	$78,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.996896 ***
	.dword 	$ff349385
	.byte 	$80,$0
	.byte 	1     ; *** Load Float -5.86590576171875e-06 ***
	.dword 	$c4d3bf2f
	.byte 	$6f,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -169947.49668598542 ***
	.dword 	$a5f6dfc9
	.byte 	$92,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.188442 ***
	.dword 	$9303dbc2
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -7.45483636856079e-08 ***
	.dword 	$a0176577
	.byte 	$69,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -6.849833159201145e-07 ***
	.dword 	$b7dfb1ee
	.byte 	$6c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -24287181065.4208 ***
	.dword 	$b4f41f21
	.byte 	$a3,$80
	.byte 	1     ; *** Load Float -24287181065.4208 ***
	.dword 	$b4f41f21
	.byte 	$a3,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 842.65 ***
	.dword 	$d2a99999
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.012346 ***
	.dword 	$903291b8
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 867.33 ***
	.dword 	$d8d51eb8
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -858.3176540000001 ***
	.dword 	$d6945471
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0454823970794678e-08 ***
	.dword 	$afb4a233
	.byte 	$67,$0
	.byte 	1     ; *** Load Float 2.0454823970794678e-08 ***
	.dword 	$afb4a233
	.byte 	$67,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 848.44 ***
	.dword 	$d41c28f5
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -247.0 ***
	.dword 	$f7000000
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
