; Using seed 465224
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
	.byte 	1     ; *** Load Float 7.017803 ***
	.dword 	$e091d798
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -7.136324711609631e-12 ***
	.dword 	$fb164c72
	.byte 	$5b,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5.00813209701082e-11 ***
	.dword 	$dc428dfb
	.byte 	$5e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -874.0198399999999 ***
	.dword 	$da81450e
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -874.0198399999999 ***
	.dword 	$da81450e
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 120.3 ***
	.dword 	$f0999999
	.byte 	$87,$0
	.byte 	1     ; *** Load Float 6.55696 ***
	.dword 	$d1d29dc7
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 113.74304 ***
	.dword 	$e37c6fbd
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 72175813528146.4 ***
	.dword 	$83497b74
	.byte 	$af,$0
	.byte 	1     ; *** Load Float 7.685648597544059e-13 ***
	.dword 	$d854ef45
	.byte 	$58,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 72175813528146.4 ***
	.dword 	$83497b74
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 878.44 ***
	.dword 	$db9c28f5
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -601.43 ***
	.dword 	$965b851e
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -0.000231041259765625 ***
	.dword 	$f243aa79
	.byte 	$74,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -601.4302310412597 ***
	.dword 	$965b88e7
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7527423729521.918 ***
	.dword 	$db13ad5b
	.byte 	$ab,$0
	.byte 	1     ; *** Load Float 536.01 ***
	.dword 	$8600a3d7
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 7527423730057.928 ***
	.dword 	$db13ad5c
	.byte 	$ab,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1330.253824 ***
	.dword 	$a6481f53
	.byte 	$8b,$0
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -166.281728 ***
	.dword 	$a6481f53
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -567.5 ***
	.dword 	$8de00000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -8441029931273.553 ***
	.dword 	$f5aa92e6
	.byte 	$ab,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6179308124659.254 ***
	.dword 	$b3d76ee7
	.byte 	$ab,$80
	.byte 	1     ; *** Load Float -1006.1250560000001 ***
	.dword 	$fb8800ea
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 6217156732964047.0 ***
	.dword 	$b0b3c4d4
	.byte 	$b5,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.23 ***
	.dword 	$875c28f5
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 72.49 ***
	.dword 	$90fae147
	.byte 	$87,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.058352876258794324 ***
	.dword 	$ef036cf2
	.byte 	$7c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -809.0 ***
	.dword 	$ca400000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 2.171265 ***
	.dword 	$8af60179
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -811.171265 ***
	.dword 	$cacaf601
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.665981650352478e-09 ***
	.dword 	$b73471f7
	.byte 	$64,$0
	.byte 	1     ; *** Load Float -30.6 ***
	.dword 	$f4cccccc
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -33770.04544 ***
	.dword 	$83ea0ba1
	.byte 	$90,$80
	.byte 	1     ; *** Load Float -33770.04544 ***
	.dword 	$83ea0ba1
	.byte 	$90,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 819.26 ***
	.dword 	$ccd0a3d7
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.013426750970387912 ***
	.dword 	$dbfbe013
	.byte 	$7a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.019968 ***
	.dword 	$828e4fb9
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8444341.911552 ***
	.dword 	$80d9b5e9
	.byte 	$98,$0
	.byte 	1     ; *** Load Float 0.181606 ***
	.dword 	$b9f6ec5b
	.byte 	$7e,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.478911 ***
	.dword 	$f533d295
	.byte 	$7f,$0
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -14.521089 ***
	.dword 	$e856616b
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.373037 ***
	.dword 	$befeb4a6
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 15.626963 ***
	.dword 	$fa080a5a
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.7385864257812504e-06 ***
	.dword 	$b7c88e79
	.byte 	$6e,$0
	.byte 	1     ; *** Load Float 712.36 ***
	.dword 	$b2170a3d
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0019508594262695315 ***
	.dword 	$ffb3fade
	.byte 	$77,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.596099376678466e-08 ***
	.dword 	$a31fff79
	.byte 	$69,$0
	.byte 	1     ; *** Load Float 173.51 ***
	.dword 	$ad828f5c
	.byte 	$88,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 4.377902931634181e-10 ***
	.dword 	$f0ad819b
	.byte 	$61,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.280726 ***
	.dword 	$c8fbb517
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.2561452 ***
	.dword 	$a0c95dac
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.000910037109375 ***
	.dword 	$ee8f8e7d
	.byte 	$76,$80
	.byte 	1     ; *** Load Float 12.0 ***
	.dword 	$c0000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 11.999089962890626 ***
	.dword 	$bffc45c1
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 170.85 ***
	.dword 	$aad99999
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1708.5 ***
	.dword 	$d5900000
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2249.125888 ***
	.dword 	$8c9203a3
	.byte 	$8c,$0
	.byte 	1     ; *** Load Float 1.4541263226419688e-11 ***
	.dword 	$ffd00713
	.byte 	$5c,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -895.3 ***
	.dword 	$dfd33333
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -915.3 ***
	.dword 	$e4d33333
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.793851 ***
	.dword 	$e59ce8d9
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 5.133580416440965e-10 ***
	.dword 	$8d1c5c57
	.byte 	$62,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 353.22 ***
	.dword 	$b09c28f5
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -0.609302 ***
	.dword 	$9bfb3743
	.byte 	$80,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.740255 ***
	.dword 	$af605681
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 6.977575 ***
	.dword 	$df484b5d
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 9.71783 ***
	.dword 	$9b7c3b4f
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.116488 ***
	.dword 	$a3ba450a
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1.1235329111514147e-14 ***
	.dword 	$ca65cf67
	.byte 	$52,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 5.116487999999989 ***
	.dword 	$a3ba450a
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -609.35 ***
	.dword 	$98566666
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -619.35 ***
	.dword 	$9ad66666
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.106769561767577e-07 ***
	.dword 	$f4753e70
	.byte 	$6c,$80
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 8.999999089323044 ***
	.dword 	$8fffff0b
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 304.0 ***
	.dword 	$98000000
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 3.4182510375976564e-06 ***
	.dword 	$e5651b0c
	.byte 	$6e,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -6.000003418251038 ***
	.dword 	$c000072b
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 428.48 ***
	.dword 	$d63d70a3
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.017817107320297e-16 ***
	.dword 	$adf71eaf
	.byte 	$4d,$80
	.byte 	1     ; *** Load Float 840.35 ***
	.dword 	$d2166666
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 853.24 ***
	.dword 	$d54f5c28
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 15358.32 ***
	.dword 	$eff947ae
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 5.934681 ***
	.dword 	$bde8e820
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -630598505831.8582 ***
	.dword 	$92d29995
	.byte 	$a8,$80
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 37094029754.815186 ***
	.dword 	$8a2f9f9b
	.byte 	$a4,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.899333 ***
	.dword 	$9cc755ff
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.23753662109375e-05 ***
	.dword 	$cf9fcb0c
	.byte 	$70,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 395893.9813570858 ***
	.dword 	$c14ebf67
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 75324.194816 ***
	.dword 	$931e18ef
	.byte 	$91,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -75336.194816 ***
	.dword 	$932418ef
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16828643938.402304 ***
	.dword 	$fac42e98
	.byte 	$a2,$0
	.byte 	1     ; *** Load Float 16828643938.402304 ***
	.dword 	$fac42e98
	.byte 	$a2,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 33657287876.804607 ***
	.dword 	$fac42e98
	.byte 	$a3,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 77307.57632 ***
	.dword 	$96fdc9c4
	.byte 	$91,$0
	.byte 	1     ; *** Load Float -1.9129482097923755e-11 ***
	.dword 	$a843c3a4
	.byte 	$5d,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 77307.57631999998 ***
	.dword 	$96fdc9c4
	.byte 	$91,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -657.03 ***
	.dword 	$a441eb85
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 883.41 ***
	.dword 	$dcda3d70
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.83613121509552e-10 ***
	.dword 	$bbe8ff32
	.byte 	$62,$0
	.byte 	1     ; *** Load Float -1.7746799585438565e-15 ***
	.dword 	$ffc2224e
	.byte 	$4f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 6.836148961895105e-10 ***
	.dword 	$bbe91f2a
	.byte 	$62,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 3.8932132720947267e-07 ***
	.dword 	$d103ea70
	.byte 	$6b,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.158343 ***
	.dword 	$828892ab
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 2.536989 ***
	.dword 	$a25e071c
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.21575812902618 ***
	.dword 	$cdcefb2f
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 11824130452917.059 ***
	.dword 	$ac105186
	.byte 	$ac,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.1840194131608338e-12 ***
	.dword 	$a6a2cb8b
	.byte 	$59,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.870793 ***
	.dword 	$8deec4a4
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -859.59 ***
	.dword 	$d6e5c28f
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.010319795483893484 ***
	.dword 	$a9145c06
	.byte 	$7a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8344255315843.22 ***
	.dword 	$f2d98bf7
	.byte 	$ab,$0
	.byte 	1     ; *** Load Float 9280015577.382912 ***
	.dword 	$8a487336
	.byte 	$a2,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 899.1639341834393 ***
	.dword 	$e0ca7de5
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 648.62 ***
	.dword 	$a227ae14
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 0.725865 ***
	.dword 	$b9d249e4
	.byte 	$80,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 470.8105563 ***
	.dword 	$eb67c04f
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -556.5 ***
	.dword 	$8b200000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -0.842877 ***
	.dword 	$d7c6c97d
	.byte 	$80,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 660.238682512395 ***
	.dword 	$a50f4693
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -677.47 ***
	.dword 	$a95e147a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -203.89 ***
	.dword 	$cbe3d70a
	.byte 	$88,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.2222222222222222 ***
	.dword 	$e38e38e3
	.byte 	$7e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 357937742.61043197 ***
	.dword 	$aaad9274
	.byte 	$9d,$0
	.byte 	1     ; *** Load Float 4.973392 ***
	.dword 	$9f2606fa
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 71970546.98492135 ***
	.dword 	$8945de5f
	.byte 	$9b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -497.54 ***
	.dword 	$f8c51eb8
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 404.99 ***
	.dword 	$ca7eb851
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -92.55000000000001 ***
	.dword 	$b9199999
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.000187981689453125 ***
	.dword 	$c51cf355
	.byte 	$74,$0
	.byte 	1     ; *** Load Float -2.4219818115234376e-06 ***
	.dword 	$a28954a7
	.byte 	$6e,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 0.00018555970764160156 ***
	.dword 	$c292ce03
	.byte 	$74,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.0963203907012945e-09 ***
	.dword 	$f3d3e4ef
	.byte 	$65,$80
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -7.0963203907012945e-09 ***
	.dword 	$f3d3e4ef
	.byte 	$65,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.677692413330078e-06 ***
	.dword 	$e12d1287
	.byte 	$6d,$0
	.byte 	1     ; *** Load Float -0.473494 ***
	.dword 	$f26dce39
	.byte 	$7f,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -3.5432178936376767e-06 ***
	.dword 	$edc80518
	.byte 	$6e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.45029223151505e-11 ***
	.dword 	$d787ad08
	.byte 	$5d,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -18.999999999975497 ***
	.dword 	$97ffffff
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 2.449329 ***
	.dword 	$9cc1ce6c
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 21.449329 ***
	.dword 	$ab9839cd
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 370.83 ***
	.dword 	$b96a3d70
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 9.922441 ***
	.dword 	$9ec2517e
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3679.5387960299995 ***
	.dword 	$e5f89ee8
	.byte 	$8c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.445458 ***
	.dword 	$97209891
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.829259 ***
	.dword 	$8d44a515
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.069790567928747 ***
	.dword 	$88eee5b7
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	1     ; *** Load Float 3.237703 ***
	.dword 	$cf3686a4
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 2.237703 ***
	.dword 	$8f3686a4
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.015886 ***
	.dword 	$904111ad
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -579.61 ***
	.dword 	$90e70a3d
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.017029 ***
	.dword 	$e08b8066
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -11.982971 ***
	.dword 	$bfba3fcc
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13981125.18144 ***
	.dword 	$d555c52e
	.byte 	$98,$80
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -13981120.18144 ***
	.dword 	$d555c02e
	.byte 	$98,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.472022 ***
	.dword 	$978d66f0
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -562.55 ***
	.dword 	$8ca33333
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.146929 ***
	.dword 	$96748e47
	.byte 	$7e,$0
	.byte 	1     ; *** Load Float 0.146929 ***
	.dword 	$96748e47
	.byte 	$7e,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.5862678992561995e-12 ***
	.dword 	$df3f52fc
	.byte 	$59,$80
	.byte 	1     ; *** Load Float 8.251220703125e-06 ***
	.dword 	$8a6eb91b
	.byte 	$70,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.3088646531045355e-17 ***
	.dword 	$f17162bc
	.byte 	$48,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.99620532989502e-08 ***
	.dword 	$aba2be05
	.byte 	$68,$0
	.byte 	1     ; *** Load Float -1.6426433546712359e-15 ***
	.dword 	$ecbad7d7
	.byte 	$4f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 3.996205494159355e-08 ***
	.dword 	$aba2be7b
	.byte 	$68,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -67678484.037632 ***
	.dword 	$81162281
	.byte 	$9b,$80
	.byte 	1     ; *** Load Float -218.85 ***
	.dword 	$dad99999
	.byte 	$88,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float 0.842156 ***
	.dword 	$d797891e
	.byte 	$80,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.377422332763672e-07 ***
	.dword 	$fbb927d4
	.byte 	$6c,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -4.935485438296669e-08 ***
	.dword 	$d3fa3c7c
	.byte 	$68,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11561584668390.195 ***
	.dword 	$a83e425a
	.byte 	$ac,$80
	.byte 	1     ; *** Load Float 2.7505798339843747e-06 ***
	.dword 	$b8969a0a
	.byte 	$6e,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -4.203326340701978e+18 ***
	.dword 	$e954dc25
	.byte 	$be,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 159.28 ***
	.dword 	$9f47ae14
	.byte 	$88,$0
	.byte 	1     ; *** Load Float -886.3641600000001 ***
	.dword 	$dd974e65
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.1797004066590418 ***
	.dword 	$b8036226
	.byte 	$7e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 781.01 ***
	.dword 	$c340a3d7
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -768.01 ***
	.dword 	$c000a3d7
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -538.97 ***
	.dword 	$86be147a
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 545.97 ***
	.dword 	$887e147a
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -78.44 ***
	.dword 	$9ce147ae
	.byte 	$87,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -78.44 ***
	.dword 	$9ce147ae
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11686159335.817215 ***
	.dword 	$ae2328f9
	.byte 	$a2,$0
	.byte 	1     ; *** Load Float -186797954588.21326 ***
	.dword 	$adf81a58
	.byte 	$a6,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2.1829506609226085e+21 ***
	.dword 	$ecad0d58
	.byte 	$c7,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.136498 ***
	.dword 	$822f1886
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -3.06498009194911e-14 ***
	.dword 	$8a08d089
	.byte 	$54,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 8.13649800000003 ***
	.dword 	$822f1886
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -292.04 ***
	.dword 	$92051eb8
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 4380.6 ***
	.dword 	$88e4cccc
	.byte 	$8d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.131915867328643e-10 ***
	.dword 	$fb042528
	.byte 	$62,$80
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -17.000000000913193 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.00033162207031249997 ***
	.dword 	$addd8f92
	.byte 	$75,$80
	.byte 	1     ; *** Load Float -731.95 ***
	.dword 	$b6fccccc
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 4.530665623505703e-07 ***
	.dword 	$f33cfe82
	.byte 	$6b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 916.12 ***
	.dword 	$e507ae14
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -925.12 ***
	.dword 	$e747ae14
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -541.25 ***
	.dword 	$87500000
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5412.5 ***
	.dword 	$a9240000
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.318931 ***
	.dword 	$94695d91
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -692.98 ***
	.dword 	$ad3eb851
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0033463173540361916 ***
	.dword 	$db4de398
	.byte 	$78,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -659.94 ***
	.dword 	$a4fc28f5
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.02424462829954238 ***
	.dword 	$c69cabb4
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 25513384470263.1 ***
	.dword 	$b9a261bf
	.byte 	$ad,$0
	.byte 	1     ; *** Load Float -64434.33984 ***
	.dword 	$fbb256ff
	.byte 	$90,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 627.91 ***
	.dword 	$9cfa3d70
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.009555509547546623 ***
	.dword 	$9c8eb640
	.byte 	$7a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 978.72 ***
	.dword 	$f4ae147a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 968.72 ***
	.dword 	$f22e147a
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.936636 ***
	.dword 	$fdf8ec0f
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.989348 ***
	.dword 	$bfa8bd23
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 47.535274953328 ***
	.dword 	$be241f1e
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 220.47 ***
	.dword 	$dc7851eb
	.byte 	$88,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.031750351521748994 ***
	.dword 	$820ca816
	.byte 	$7c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.708012 ***
	.dword 	$9b540464
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 766.15 ***
	.dword 	$bf899999
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 7437.7933938 ***
	.dword 	$e86e58de
	.byte 	$8d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 34.0 ***
	.dword 	$88000000
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 2.367767 ***
	.dword 	$97897e99
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.380143 ***
	.dword 	$ec2a21a7
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -8.619857 ***
	.dword 	$89eaef2c
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 943.25 ***
	.dword 	$ebd00000
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -926.25 ***
	.dword 	$e7900000
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 582.65 ***
	.dword 	$91a99999
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 987.5 ***
	.dword 	$f6e00000
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.5900253164556962 ***
	.dword 	$970be62d
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 7.526913 ***
	.dword 	$f0dc78a6
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.3285659074311076 ***
	.dword 	$aa0e7299
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.862801 ***
	.dword 	$fb9c10d7
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.061793 ***
	.dword 	$a1fa3550
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.5533628103717398 ***
	.dword 	$c6d497b2
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.849878 ***
	.dword 	$8d9919ac
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2.9499593333333336 ***
	.dword 	$bccc223b
	.byte 	$82,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -86.58 ***
	.dword 	$ad28f5c2
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 265.33 ***
	.dword 	$84aa3d70
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 178.75 ***
	.dword 	$b2c00000
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -523.17 ***
	.dword 	$82cae147
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 3.0663 ***
	.dword 	$c43e425a
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0001014862060546875 ***
	.dword 	$d4d4fdf3
	.byte 	$73,$0
	.byte 	1     ; *** Load Float 5.405923 ***
	.dword 	$acfd523b
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.877315049709134e-05 ***
	.dword 	$9d7b08a1
	.byte 	$71,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.88733 ***
	.dword 	$bc6501e2
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -0.594301 ***
	.dword 	$98241c3e
	.byte 	$80,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 5.293029000000001 ***
	.dword 	$a9607e5a
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -814.95 ***
	.dword 	$cbbccccc
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 5.649132 ***
	.dword 	$b4c5b078
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -650.56 ***
	.dword 	$a2a3d70a
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -646.56 ***
	.dword 	$a1a3d70a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.142391 ***
	.dword 	$a48e7792
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -116618460550945.31 ***
	.dword 	$d420b3d4
	.byte 	$af,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -116618460550940.17 ***
	.dword 	$d420b3d4
	.byte 	$af,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 459797.430272 ***
	.dword 	$e082adc4
	.byte 	$93,$0
	.byte 	1     ; *** Load Float 0.569829 ***
	.dword 	$91e05037
	.byte 	$80,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 262005.90989446352 ***
	.dword 	$ffdd7a3b
	.byte 	$92,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1844246037640.7734 ***
	.dword 	$d6b2d0a2
	.byte 	$a9,$0
	.byte 	1     ; *** Load Float 3.820011 ***
	.dword 	$f47b0f6a
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 7045040150494.169 ***
	.dword 	$cd09a3b2
	.byte 	$ab,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1157.697536 ***
	.dword 	$90b65237
	.byte 	$8b,$80
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 15050.067968 ***
	.dword 	$eb284599
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	1     ; *** Load Float -485951910592158.6 ***
	.dword 	$dcfc3f81
	.byte 	$b1,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 485951910592157.6 ***
	.dword 	$dcfc3f81
	.byte 	$b1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.843023 ***
	.dword 	$bafa0b5e
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 22333967378.153473 ***
	.dword 	$a666a982
	.byte 	$a3,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2.616204680998817e-10 ***
	.dword 	$8fd3cebd
	.byte 	$61,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 4.04758 ***
	.dword 	$8185c67d
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -18.04758 ***
	.dword 	$9061719f
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.317282 ***
	.dword 	$8513964a
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.317282 ***
	.dword 	$8513964a
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 16.634564 ***
	.dword 	$8513964a
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.7710723876953124e-07 ***
	.dword 	$94c55432
	.byte 	$6b,$0
	.byte 	1     ; *** Load Float 658.45 ***
	.dword 	$a49ccccc
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 4.2084780738025853e-10 ***
	.dword 	$e75d103a
	.byte 	$61,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.372693 ***
	.dword 	$ebed19de
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 3.341702 ***
	.dword 	$d5de7210
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 400.0 ***
	.dword 	$c8000000
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.03969 ***
	.dword 	$80a291fb
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.03969 ***
	.dword 	$80a291fb
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 64.6366152961 ***
	.dword 	$8145f270
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 112.78 ***
	.dword 	$e18f5c28
	.byte 	$87,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 129.78 ***
	.dword 	$81c7ae14
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 22133308.653568 ***
	.dword 	$a8dd1e53
	.byte 	$99,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 243466395.189248 ***
	.dword 	$e83009b3
	.byte 	$9c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 717.36 ***
	.dword 	$b3570a3d
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 3.706693 ***
	.dword 	$ed3a7546
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 193.53099919523953 ***
	.dword 	$c187ef90
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1825.644544 ***
	.dword 	$e434a01a
	.byte 	$8b,$80
	.byte 	1     ; *** Load Float 117936748604369.66 ***
	.dword 	$d6869403
	.byte 	$af,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 117936748602544.02 ***
	.dword 	$d6869403
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -193.43 ***
	.dword 	$c16e147a
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -239708312291445.3 ***
	.dword 	$da0370cd
	.byte 	$b0,$80
	.byte 	1     ; *** Load Float -431.0 ***
	.dword 	$d7800000
	.byte 	$89,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 556167777938.3882 ***
	.dword 	$817e2ece
	.byte 	$a8,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.700172 ***
	.dword 	$9667cf1c
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -3.681640625e-06 ***
	.dword 	$f7121ab4
	.byte 	$6e,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.73043441796875e-05 ***
	.dword 	$9128cbd1
	.byte 	$71,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 500.55 ***
	.dword 	$fa466666
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -500.55 ***
	.dword 	$fa466666
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 8.876309 ***
	.dword 	$8e055c96
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -9.123691 ***
	.dword 	$91faa369
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 8.515029 ***
	.dword 	$883d8f0c
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.5871970606324417 ***
	.dword 	$96528beb
	.byte 	$80,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.185197 ***
	.dword 	$cbda4484
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -24773096485.42106 ***
	.dword 	$b892ee84
	.byte 	$a3,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0258782973978667e-13 ***
	.dword 	$e2a30553
	.byte 	$57,$0
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 13.000000000000403 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.432867 ***
	.dword 	$adda0be5
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 38.030069 ***
	.dword 	$981eca68
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7945758217.076736 ***
	.dword 	$eccd5304
	.byte 	$a1,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.841627 ***
	.dword 	$f5dd377e
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 4.173103 ***
	.dword 	$858a0f4d
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 8.01473 ***
	.dword 	$803c5586
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.523449 ***
	.dword 	$98600c0f
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -1059.078144 ***
	.dword 	$84628027
	.byte 	$8b,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 1068.601593 ***
	.dword 	$8593403f
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -781252403.658752 ***
	.dword 	$ba43dcce
	.byte 	$9e,$80
	.byte 	1     ; *** Load Float 224.78 ***
	.dword 	$e0c7ae14
	.byte 	$88,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -781252178.878752 ***
	.dword 	$ba43d94b
	.byte 	$9e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -493.17 ***
	.dword 	$f695c28f
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 37.93615384615385 ***
	.dword 	$97be9f1d
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -74.02 ***
	.dword 	$940a3d70
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 4.290457 ***
	.dword 	$894b6c7a
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -17.25224142789451 ***
	.dword 	$8a049727
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 980.4 ***
	.dword 	$f5199999
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 1.809861 ***
	.dword 	$e7a98676
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2129611086490.501 ***
	.dword 	$f7eb5b2d
	.byte 	$a9,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -2129611086490.501 ***
	.dword 	$f7eb5b2d
	.byte 	$a9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.418243408203125e-07 ***
	.dword 	$9171e29b
	.byte 	$6c,$0
	.byte 	1     ; *** Load Float -91500759529193.2 ***
	.dword 	$a6705c89
	.byte 	$af,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -91500759529193.2 ***
	.dword 	$a6705c89
	.byte 	$af,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 33130106411.024384 ***
	.dword 	$f6d6a9c5
	.byte 	$a3,$0
	.byte 	1     ; *** Load Float -8.205652236938477e-09 ***
	.dword 	$8cf8d716
	.byte 	$66,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -271.854131781632 ***
	.dword 	$87ed5430
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -715.27 ***
	.dword 	$b2d147ae
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5006.889999999999 ***
	.dword 	$9c771eb8
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.000137855712890625 ***
	.dword 	$908d5c74
	.byte 	$74,$80
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -905.37 ***
	.dword 	$e257ae14
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 247.15 ***
	.dword 	$f7266666
	.byte 	$88,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -658.22 ***
	.dword 	$a48e147a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.609937012195587e-09 ***
	.dword 	$c0c1871e
	.byte 	$65,$80
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1.999999994390063 ***
	.dword 	$fffffff3
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 877.18 ***
	.dword 	$db4b851e
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 5.714883 ***
	.dword 	$b6e05250
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -0.290852 ***
	.dword 	$94ea8da7
	.byte 	$7f,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -4.290852 ***
	.dword 	$894ea8da
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.333333333333333 ***
	.dword 	$caaaaaaa
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1483672.12544 ***
	.dword 	$b51cc100
	.byte 	$95,$0
	.byte 	1     ; *** Load Float 900.14 ***
	.dword 	$e108f5c2
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 646.12 ***
	.dword 	$a187ae14
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 653.12 ***
	.dword 	$a347ae14
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -305.28 ***
	.dword 	$98a3d70a
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 168170303468.3392 ***
	.dword 	$9c9eecbf
	.byte 	$a6,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 168170303163.0592 ***
	.dword 	$9c9eecba
	.byte 	$a6,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -37.19 ***
	.dword 	$94c28f5c
	.byte 	$86,$80
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -371.9 ***
	.dword 	$b9f33333
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.3695498637389391e-12 ***
	.dword 	$c0bf3bea
	.byte 	$59,$0
	.byte 	1     ; *** Load Float -101024.39936 ***
	.dword 	$c550331e
	.byte 	$91,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.3556624661123242e-17 ***
	.dword 	$fa135994
	.byte 	$48,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -147.45 ***
	.dword 	$93733333
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 4.458432085812092e-10 ***
	.dword 	$f51ada76
	.byte 	$61,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -330721646448.8151 ***
	.dword 	$9a0117ae
	.byte 	$a7,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -89274292463411.92 ***
	.dword 	$a26394fa
	.byte 	$af,$80
	.byte 	1     ; *** Load Float 2.89799 ***
	.dword 	$b978ab0c
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -258716006816043.12 ***
	.dword 	$eb4d03af
	.byte 	$b0,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20877973464.80947 ***
	.dword 	$9b8d92fb
	.byte 	$a3,$0
	.byte 	1     ; *** Load Float 8.217516 ***
	.dword 	$837af20e
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 20877973473.02699 ***
	.dword 	$9b8d92fc
	.byte 	$a3,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.756613 ***
	.dword 	$b8362c77
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -274200.526848 ***
	.dword 	$85e310db
	.byte 	$93,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1578466.317460046 ***
	.dword 	$c0af128a
	.byte 	$95,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 997.94 ***
	.dword 	$f97c28f5
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -1010.94 ***
	.dword 	$fcbc28f5
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.140854 ***
	.dword 	$8481e03f
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 182.04 ***
	.dword 	$b60a3d70
	.byte 	$88,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -177.899146 ***
	.dword 	$b1e62e6e
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.00075890625 ***
	.dword 	$c6f15619
	.byte 	$76,$80
	.byte 	1     ; *** Load Float -231281721146.86774 ***
	.dword 	$d765dbfc
	.byte 	$a6,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 26256548777523.414 ***
	.dword 	$bf0aa21a
	.byte 	$ad,$0
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 210052390220187.3 ***
	.dword 	$bf0aa21a
	.byte 	$b0,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.1981242664660387e-15 ***
	.dword 	$acaafbc1
	.byte 	$4f,$0
	.byte 	1     ; *** Load Float -1.32906308181191e-15 ***
	.dword 	$bf89c5e6
	.byte 	$4f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 2.5271873482779486e-15 ***
	.dword 	$b61a60d4
	.byte 	$50,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 923.74 ***
	.dword 	$e6ef5c28
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 6.821513 ***
	.dword 	$da49d5a1
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.288867 ***
	.dword 	$a4f99806
	.byte 	$81,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 2.7111330000000002 ***
	.dword 	$ad8333fc
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.427579 ***
	.dword 	$9b5d744f
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 8.387874 ***
	.dword 	$8634bb5e
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.2894152916460119 ***
	.dword 	$942e3db9
	.byte 	$7f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.45528 ***
	.dword 	$dd234eb9
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -5.54472 ***
	.dword 	$b16e58a3
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.25252685546875e-05 ***
	.dword 	$dc4e93e1
	.byte 	$72,$80
	.byte 	1     ; *** Load Float -517.13 ***
	.dword 	$814851eb
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -517.1300525252685 ***
	.dword 	$814852c7
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -0.478786 ***
	.dword 	$f5237047
	.byte 	$7f,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.99 ***
	.dword 	$a7eb851e
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 724.96 ***
	.dword 	$b53d70a3
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -703.97 ***
	.dword 	$affe147a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.581062 ***
	.dword 	$92980f55
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -8275613.450239999 ***
	.dword 	$fc8d3ae6
	.byte 	$97,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -8275608.869177999 ***
	.dword 	$fc8d31bd
	.byte 	$97,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4719244643902.947 ***
	.dword 	$89591cd1
	.byte 	$ab,$0
	.byte 	1     ; *** Load Float 4719244643902.947 ***
	.dword 	$89591cd1
	.byte 	$ab,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 9438489287805.895 ***
	.dword 	$89591cd1
	.byte 	$ac,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1465855708011.43 ***
	.dword 	$aaa5e785
	.byte 	$a9,$80
	.byte 	1     ; *** Load Float 967.59 ***
	.dword 	$f1e5c28f
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -1465855708979.02 ***
	.dword 	$aaa5e787
	.byte 	$a9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.141832 ***
	.dword 	$9244f1a1
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.141832 ***
	.dword 	$9244f1a1
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.791649 ***
	.dword 	$e554c122
	.byte 	$81,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 4.208351 ***
	.dword 	$86aacfb7
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 78251143037.19016 ***
	.dword 	$91c10d7b
	.byte 	$a5,$0
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1095516002520.6621 ***
	.dword 	$ff11d798
	.byte 	$a8,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -9.263967370998217e-17 ***
	.dword 	$d59ccfae
	.byte 	$4b,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2.158902249873204e+17 ***
	.dword 	$bfbfc102
	.byte 	$ba,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -0.248834 ***
	.dword 	$fece5710
	.byte 	$7e,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.891129 ***
	.dword 	$fc8420f6
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1.1088709999999997 ***
	.dword 	$8def7c24
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6858593.009664 ***
	.dword 	$d14ec204
	.byte 	$97,$80
	.byte 	1     ; *** Load Float 8.375873 ***
	.dword 	$86039368
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -818851.1227025529 ***
	.dword 	$c7ea31f6
	.byte 	$94,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.397483825683594e-07 ***
	.dword 	$e16b11c6
	.byte 	$6c,$0
	.byte 	1     ; *** Load Float -8.589442586526276e-12 ***
	.dword 	$971b6912
	.byte 	$5c,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -97765.17790404937 ***
	.dword 	$bef296c5
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.982943 ***
	.dword 	$8fba2270
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 4.824524 ***
	.dword 	$9a628027
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 13.807467 ***
	.dword 	$dceb6284
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -134646.071296 ***
	.dword 	$837d8490
	.byte 	$92,$80
	.byte 	1     ; *** Load Float -134646.071296 ***
	.dword 	$837d8490
	.byte 	$92,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.955309 ***
	.dword 	$9e91e42e
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -840.28 ***
	.dword 	$d211eb85
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -4163.84704652 ***
	.dword 	$821ec6c0
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.319111 ***
	.dword 	$946c508b
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 995.14 ***
	.dword 	$f8c8f5c2
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.002330436923447957 ***
	.dword 	$98ba3e5f
	.byte 	$78,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 298665841010.9338 ***
	.dword 	$8b13be22
	.byte 	$a7,$0
	.byte 	1     ; *** Load Float 77138149.507072 ***
	.dword 	$93211cb0
	.byte 	$9b,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2.3038530296556806e+19 ***
	.dword 	$9fdca69e
	.byte 	$c1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 30761414767.411198 ***
	.dword 	$e530be0d
	.byte 	$a3,$0
	.byte 	1     ; *** Load Float 9.184277 ***
	.dword 	$92f2cc70
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.765948688145727e-12 ***
	.dword 	$a7afd976
	.byte 	$5b,$80
	.byte 	1     ; *** Load Float 127663195589.44357 ***
	.dword 	$edca8e2e
	.byte 	$a5,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -3.733220577896784e-23 ***
	.dword 	$b4870844
	.byte 	$36,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.678669 ***
	.dword 	$9adbd406
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -7386.6608639999995 ***
	.dword 	$e6d54973
	.byte 	$8d,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -7376.982195 ***
	.dword 	$e687db89
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.272357 ***
	.dword 	$945b9303
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -0.970295 ***
	.dword 	$f86540cc
	.byte 	$80,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -9.55622465332708 ***
	.dword 	$98e64bd2
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -691.85 ***
	.dword 	$acf66666
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 592.29 ***
	.dword 	$94128f5c
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.1680933326579885 ***
	.dword 	$95841513
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
